services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: hotel
      POSTGRES_USER: lukasz
      POSTGRES_PASSWORD: lukasz1986@@!!
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: openjdk:21-jdk
    working_dir: /app
    volumes:
      - C:\Users\bazel\IdeaProjects\hotel-reservation\app:/app
    command: ["java", "-jar", "hotel-reservation-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hotel
      SPRING_DATASOURCE_USERNAME: lukasz
      SPRING_DATASOURCE_PASSWORD: lukasz1986@@!!

volumes:
  postgres_data: