version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - postgres.env
    environment:
      POSTGRES_DB: hotel
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
