services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: hotel
      POSTGRES_USER: lukasz
      POSTGRES_PASSWORD: lukasz1986@@!!
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: